version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t yolov5 .
      - docker tag yolov5:latest 401975321526.dkr.ecr.us-east-1.amazonaws.com/yolov5:latest  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 401975321526.dkr.ecr.us-east-1.amazonaws.com/yolov5:latest
      